import "./globals.css";
import "@/firebase/firebase";
export const metadata = {
  title: "Sahyaan Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
