import React from "react";
import Dashboard from "./dashboard";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

function page() {
  return <Dashboard/>;
}

export default page;
